# Generated by Django 4.0.4 on 2022-05-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='uuid',
            new_name='id',
        ),
    ]
